default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    app_identifier = ENV['IOS_BUNDLE_ID']
    apple_id = ENV['IOS_APPLE_ID']
    team_id = ENV['IOS_TEAM_ID']

    build_app(
      workspace: "ios/something_new_mobile.xcworkspace",
      scheme: "something_new_mobile",
      export_method: "app-store",
      include_bitcode: false,
      include_symbols: true,
      clean: true
    )

    upload_to_testflight(
      username: apple_id,
      team_id: team_id,
      skip_waiting_for_build_processing: false
    )
  end
end
